export const AUTH_TOKEN = 'auth_token'
export const AUTH_ACC_TOKEN = '@auth/access_token'
export const AUTH_ID_TOKEN = '@auth/id_token'
export const AUTH_REFRESH_TOKEN = '@auth/refresh_token'
export const AUTH_STORAGE = '@auth'
export const KEYCLOAK_INFO = '@keycloak/info'